package com.kosaai.classification

import org.junit.Assert.assertTrue
import org.junit.Test
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.util.zip.GZIPInputStream
import kotlin.math.abs

class RgbPreprocessorTest {
  @Test fun matchesPillowBilinearCenterCropReference() {
    // Goldens generated by Pillow, not by the Kotlin implementation under test.
    for ((width, height) in listOf(320 to 480, 480 to 321, 13 to 5, 224 to 224)) {
      val rgb = ByteArray(width * height * 3)
      for (y in 0 until height) for (x in 0 until width) {
        val index = (y * width + x) * 3
        rgb[index] = ((x * 7 + y * 3) % 256).toByte()
        rgb[index + 1] = (if ((x / 3 + y / 5) % 2 == 0) 255 else 0).toByte()
        rgb[index + 2] = ((x * 2 + y * 11) % 256).toByte()
      }
      val input = ByteBuffer.allocateDirect(224 * 224 * 3 * 4).order(ByteOrder.nativeOrder())
      val preprocessor = RgbPreprocessor()
      preprocessor.writeInput(rgb, width, height, input)
      val expected = GZIPInputStream(requireNotNull(javaClass.getResourceAsStream("/pillow-${width}x${height}.rgb.gz"))).use { it.readBytes() }
      for (index in expected.indices) {
        val actual = input.float
        val reference = (expected[index].toInt() and 255) / 255f
        assertTrue("$width x $height: RGB/NHWC index $index: $actual vs $reference", abs(actual - reference) <= 1.01f / 255f)
        assertTrue(actual in 0f..1f)
      }
      assertTrue(!input.hasRemaining())
      // Reusing shape-specific coefficients and buffers gives identical results.
      preprocessor.writeInput(rgb, width, height, input)
      assertTrue(input.position() == 0 && input.remaining() == 224 * 224 * 3 * 4)
    }
  }
}
